version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Drogobeats1995*
      POSTGRES_DB: music_share
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Drogobeats1995*
      DB_NAME: music_share
      DB_SSL_MODE: disable
      JWT_SECRET: your-super-secret-key
      SERVER_PORT: 10000
    ports:
      - "10000:10000"
    depends_on:
      - postgres

volumes:
  postgres_data: